name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip project
        run: unzip Election_Market_BD_FULL_FLUTTER.zip

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Build APK
        run: |
          cd Election_Market_BD_FULL_FLUTTER
          flutter pub get
          flutter build apk

      - uses: actions/upload-artifact@v3
        with:
          name: Election-Market-BD-APK
          path: Election_Market_BD_FULL_FLUTTER/build/app/outputs/flutter-apk/app-release.apk
